version: '3'

services:
  whatsapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    env_file: .env
    environment:
      - TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN
    ports:
      - "80:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - traefik-net
    deploy:
      mode: replicated
      replicas: 3
      labels:
       - traefik.port=3000
       - traefik.docker.network=proxy
       - traefik.frontend.rule=Host:node-app.cometari.com
      resources:
        limits:
         memory: 128M
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN
    ports:
      - "80:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js


    